package gm2d;

class RGB
{
   public static var ZERO = RGBA(0,0xff);
   public static var CLEAR = RGBA(0,0);
   public static var BLACK  = RGBA(0,0xff);
   public static var WHITE = RGBA(0xffffff,0xff);
   public static var RED = RGBA(0xff0000,0xff);
   public static var GREEN = RGBA(0x00ff00,0xff);
   public static var BLUE = RGBA(0x0000ff,0xff);
   public static var YELLOW = RGBA(0xffff00,0xff);

   @:keep public static var aliceblue = 0xf0f8ff;
   @:keep public static var antiquewhite = 0xfaebd7;
   @:keep public static var aqua = 0x00ffff;
   @:keep public static var aquamarine = 0x7fffd4;
   @:keep public static var azure = 0xf0ffff;
   @:keep public static var beige = 0xf5f5dc;
   @:keep public static var bisque = 0xffe4c4;
   @:keep public static var black = 0x000000;
   @:keep public static var blanchedalmond = 0xffebcd;
   @:keep public static var blue = 0x0000ff;
   @:keep public static var blueviolet = 0x8a2be2;
   @:keep public static var brown = 0xa52a2a;
   @:keep public static var burlywood = 0xdeb887;
   @:keep public static var cadetblue = 0x5f9ea0;
   @:keep public static var chartreuse = 0x7fff00;
   @:keep public static var chocolate = 0xd2691e;
   @:keep public static var coral = 0xff7f50;
   @:keep public static var cornflowerblue = 0x6495ed;
   @:keep public static var cornsilk = 0xfff8dc;
   @:keep public static var crimson = 0xdc143c;
   @:keep public static var cyan = 0x00ffff;
   @:keep public static var darkblue = 0x00008b;
   @:keep public static var darkcyan = 0x008b8b;
   @:keep public static var darkgoldenrod = 0xb8860b;
   @:keep public static var darkgray = 0xa9a9a9;
   @:keep public static var darkgreen = 0x006400;
   @:keep public static var darkgrey = 0xa9a9a9;
   @:keep public static var darkkhaki = 0xbdb76b;
   @:keep public static var darkmagenta = 0x8b008b;
   @:keep public static var darkolivegreen = 0x556b2f;
   @:keep public static var darkorange = 0xff8c00;
   @:keep public static var darkorchid = 0x9932cc;
   @:keep public static var darkred = 0x8b0000;
   @:keep public static var darksalmon = 0xe9967a;
   @:keep public static var darkseagreen = 0x8fbc8f;
   @:keep public static var darkslateblue = 0x483d8b;
   @:keep public static var darkslategray = 0x2f4f4f;
   @:keep public static var darkslategrey = 0x2f4f4f;
   @:keep public static var darkturquoise = 0x00ced1;
   @:keep public static var darkviolet = 0x9400d3;
   @:keep public static var deeppink = 0xff1493;
   @:keep public static var deepskyblue = 0x00bfff;
   @:keep public static var dimgray = 0x696969;
   @:keep public static var dimgrey = 0x696969;
   @:keep public static var dodgerblue = 0x1e90ff;
   @:keep public static var firebrick = 0xb22222;
   @:keep public static var floralwhite = 0xfffaf0;
   @:keep public static var forestgreen = 0x228b22;
   @:keep public static var fuchsia = 0xff00ff;
   @:keep public static var gainsboro = 0xdcdcdc;
   @:keep public static var ghostwhite = 0xf8f8ff;
   @:keep public static var gold = 0xffd700;
   @:keep public static var goldenrod = 0xdaa520;
   @:keep public static var gray = 0x808080;
   @:keep public static var green = 0x008000;
   @:keep public static var greenyellow = 0xadff2f;
   @:keep public static var grey = 0x808080;
   @:keep public static var honeydew = 0xf0fff0;
   @:keep public static var hotpink = 0xff69b4;
   @:keep public static var indianred = 0xcd5c5c;
   @:keep public static var indigo = 0x4b0082;
   @:keep public static var ivory = 0xfffff0;
   @:keep public static var khaki = 0xf0e68c;
   @:keep public static var lavender = 0xe6e6fa;
   @:keep public static var lavenderblush = 0xfff0f5;
   @:keep public static var lawngreen = 0x7cfc00;
   @:keep public static var lemonchiffon = 0xfffacd;
   @:keep public static var lightblue = 0xadd8e6;
   @:keep public static var lightcoral = 0xf08080;
   @:keep public static var lightcyan = 0xe0ffff;
   @:keep public static var lightgoldenrodyellow = 0xfafad2;
   @:keep public static var lightgray = 0xd3d3d3;
   @:keep public static var lightgreen = 0x90ee90;
   @:keep public static var lightgrey = 0xd3d3d3;
   @:keep public static var lightpink = 0xffb6c1;
   @:keep public static var lightsalmon = 0xffa07a;
   @:keep public static var lightseagreen = 0x20b2aa;
   @:keep public static var lightskyblue = 0x87cefa;
   @:keep public static var lightslategray = 0x778899;
   @:keep public static var lightslategrey = 0x778899;
   @:keep public static var lightsteelblue = 0xb0c4de;
   @:keep public static var lightyellow = 0xffffe0;
   @:keep public static var lime = 0x00ff00;
   @:keep public static var limegreen = 0x32cd32;
   @:keep public static var linen = 0xfaf0e6;
   @:keep public static var magenta = 0xff00ff;
   @:keep public static var maroon = 0x800000;
   @:keep public static var mediumaquamarine = 0x66cdaa;
   @:keep public static var mediumblue = 0x0000cd;
   @:keep public static var mediumorchid = 0xba55d3;
   @:keep public static var mediumpurple = 0x9370db;
   @:keep public static var mediumseagreen = 0x3cb371;
   @:keep public static var mediumslateblue = 0x7b68ee;
   @:keep public static var mediumspringgreen = 0x00fa9a;
   @:keep public static var mediumturquoise = 0x48d1cc;
   @:keep public static var mediumvioletred = 0xc71585;
   @:keep public static var midnightblue = 0x191970;
   @:keep public static var mintcream = 0xf5fffa;
   @:keep public static var mistyrose = 0xffe4e1;
   @:keep public static var moccasin = 0xffe4b5;
   @:keep public static var navajowhite = 0xffdead;
   @:keep public static var navy = 0x000080;
   @:keep public static var oldlace = 0xfdf5e6;
   @:keep public static var olive = 0x808000;
   @:keep public static var olivedrab = 0x6b8e23;
   @:keep public static var orange = 0xffa500;
   @:keep public static var orangered = 0xff4500;
   @:keep public static var orchid = 0xda70d6;
   @:keep public static var palegoldenrod = 0xeee8aa;
   @:keep public static var palegreen = 0x98fb98;
   @:keep public static var paleturquoise = 0xafeeee;
   @:keep public static var palevioletred = 0xdb7093;
   @:keep public static var papayawhip = 0xffefd5;
   @:keep public static var peachpuff = 0xffdab9;
   @:keep public static var peru = 0xcd853f;
   @:keep public static var pink = 0xffc0cb;
   @:keep public static var plum = 0xdda0dd;
   @:keep public static var powderblue = 0xb0e0e6;
   @:keep public static var purple = 0x800080;
   @:keep public static var red = 0xff0000;
   @:keep public static var rosybrown = 0xbc8f8f;
   @:keep public static var royalblue = 0x4169e1;
   @:keep public static var saddlebrown = 0x8b4513;
   @:keep public static var salmon = 0xfa8072;
   @:keep public static var sandybrown = 0xf4a460;
   @:keep public static var seagreen = 0x2e8b57;
   @:keep public static var seashell = 0xfff5ee;
   @:keep public static var sienna = 0xa0522d;
   @:keep public static var silver = 0xc0c0c0;
   @:keep public static var skyblue = 0x87ceeb;
   @:keep public static var slateblue = 0x6a5acd;
   @:keep public static var slategray = 0x708090;
   @:keep public static var slategrey = 0x708090;
   @:keep public static var snow = 0xfffafa;
   @:keep public static var springgreen = 0x00ff7f;
   @:keep public static var steelblue = 0x4682b4;
   @:keep public static var tan = 0xd2b48c;
   @:keep public static var teal = 0x008080;
   @:keep public static var thistle = 0xd8bfd8;
   @:keep public static var tomato = 0xff6347;
   @:keep public static var turquoise = 0x40e0d0;
   @:keep public static var violet = 0xee82ee;
   @:keep public static var wheat = 0xf5deb3;
   @:keep public static var white = 0xffffff;
   @:keep public static var whitesmoke = 0xf5f5f5;
   @:keep public static var yellow = 0xffff00;
   @:keep public static var yellowgreen = 0x9acd32;

   public static function RGBA(inRGB:Int, inA:Int = 0xff)
   {
      return inRGB | (inA<<24);
   }

   public static function resolve(inName:String) : Null<Int>
   {
      return Reflect.field( RGB, inName);
   }

}

